### ISSUE TITLE
Wrong BTC value

### ISSUE THREAD

**Issue by resobyte** [rdemirr/TwitterBTCPricesBot#2]
Hello,
About 2 days your twitter bot shows wrong value.

![btc](https://user-images.githubusercontent.com/17431441/35718602-61fc850c-07f6-11e8-9273-09ccb5edce58.PNG)

Hopefully we will reach the BTC value in the picture.($85000) 🥇 

Good luck bro

**Comment by ramazan** [comment]
Hey!

thanks for your feedback.

i fixed this issue.

Best regards.
